version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  journal-service:
    build: ./journal-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
